/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()  //defines repositories, we can add another repository
    }
    //we don't need to activate version catalog explicitly here because we have libs.versions.toml file
}

rootProject.name = "fleet-management-system"
include("vehicle-registry-service")
include("vehicle-tracking-service")
include("alert-service")
include("common")
